config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Standard resources and paths. Tyrants has all functions, Users can't be shown in index.
  resources :tyrants, only: [:edit,:update,:new,:create]
  resources :users, only: [ :new, :create,:destroy,:update]
  resources :ratings, only: [:show]
  get "otherusers/:id", to: "users#otheruser"
  get "/comments", to: "comments#index"
  post "/comments", to: "comments#create"
  get "/ratings", to: "ratings#index"
  post "/ratings", to: "ratings#create"
  get "/tyrants", to: "tyrants#index"
  get '/', to: "tyrants#index"
  get "/tyrants/:id", to: "tyrants#show" do
   post "/ratings", to: "ratings#create"
   post "/comments", to: "comments#create"
  end
 
  # get "/ratings/:id", to: "ratings#show"

  get "/login", to: "login#new"
  post "/login", to: "login#create"
  delete '/logout', to: "login#destroy"
  get "/profile", to: "users#show"
  get "/profile/edit", to: "users#edit"
  patch "/profile", to: "users#update"
  get "/", to: "tyrants#index"
  # get "/profile:id", to: "users#show"
  #  get "/tyrants/:id/edit", to: "tyrants#edit", as: "tyrant"
  #  patch "/tyrants/:id", to: "tyrants#update" 
end
  # Need to create custom route for homepage to be index of tyrants display page

app/models/user.rb
class User < ApplicationRecord
    has_many :ratings
    has_many :tyrants, through: :ratings
    has_many :comments
    has_many :tyrants, through: :comments
    has_many :tyrants
    validates :name, length: {minimum: 3}
    validates :name, uniqueness: true
    validates :password, length: {minimum: 3}
    has_secure_password
end

app/controllers/user_controller.rb
class UsersController < ApplicationController

    before_action :current_user, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
    end

    def create
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def current_user
        @user = User.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    

    # before_action :current_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :authenticated, only: [:new,:create]
    # skip_before_action :verify_authenticity_token
    def show
        @tyrants = Tyrant.all
    end

    def new
        @user = User.new
    end

    def create
        user = User.new(user_params)
        if user.valid?
            user.save
            redirect_to '/profile'
        else
            flash[:errors] = user.errors.full_messages 
            redirect_to "/users/new"
        end
    end

    def edit
    end

    def update
        @user.update(user_params)
        redirect_to "/profile"
    end

    def destroy
    end

    def otheruser
        @users = User.find(params[:id])
    end

    private

    # def current_user
    #     @user = User.find(session[:user_id])
    # end

    def user_params
        params.require(:user).permit(:name,:password,:password_confirmation)
    end

end

app/views/users/edit.html.erb
<body>
<%= form_with model:@user do |f| %>
<%= f.label :username %>
<%= f.text_field :name %>
<%= f.label :password %>
<%= f.password_field :password%>
<%= f.label :password_confirmation%>
<%= f.password_field :password_confirmation%>
<br/>
<%= f.submit %>
<%end%>
<%= button_to "Back", '/profile',method:"get"%>
</body>

app/views/users/new.html.erb
<% if flash[:errors]%>
    <% flash[:errors].each do |e| %>
        <li style="color: red">
            <%= e %>
        </li>
    <%end%>
<%end%>

<h1>Sign Up!!</h1>
<body>
<%= form_with model:@user do |f| %>
<%= f.label :username %>
<%= f.text_field :name %>
<%= f.label :password %>
<%= f.password_field :password%>
<%= f.label :password_confirmation%>
<%= f.password_field :password_confirmation%>
<br/>
<%= f.submit %>
<%end%>

<%= button_to "Home", '/', method:"get"%>
</body>

app/views/users/otheruser.html.erb
<%= button_to "Home", '/', method:"get"%>
<h1><%=@users.name%><h1>


<h3> <%=@users.name%>'s Tyrants</h3>
<%@users.tyrants.each do |x|%>
    <ul>
    <li>
    <%= link_to x.name, tyrant_path(x.id)%><br/>
    </li>
    </ul>
   
<% end %>

<h3><%=@users.name%>'s Comments</h3>
<%@users.comments.each do |c|%>
    <ul>
    <li>
    <%= link_to c.tyrant.name, tyrant_path(c.tyrant.id)%><br/>
    <%= c.comments%>
    </li>
    </ul>
   
<% end %>
<h3><%=@users.name%>'s Reviews</h3>
<%@users.ratings.each do |x|%>
    
    <ul>
    <li>
    <%= link_to x.tyrant.name, rating_path(x.id) %><br/>
    <label>Appearance Rating:</label>
    <%= x.appearance_rating%><br/>
    <label>Economics Rating:</label>
    <%= x.economics_rating%><br/>
    <label>Social Rating:</label>
    <%= x.social_rating%><br/>
    <label>Warmongering Rating:</label>
    <%= x.warmongering_rating%><br/>
    <label>Charisma Rating:</label>
    <%= x.charisma_rating%><br/>
    </li>
    </ul>
    
    
<%end%>

app/views/users/show.html.erb
<h1>User Showpage</h1>
<body>
<h1><%=@user.name%></h1>

<br>

<br>
<%= button_to "Create Tyrant", '/tyrants/new',method:"get"%>
<%= button_to "Edit Profile", profile_edit_path, method:"get"%>
<%= button_to "Home", '/', method:"get"%>
<%= form_with url:'/logout', method: "delete" do |f|%>
<%= f.submit "Log Out"%>
<%end%>

<h3>My Tyrants</h3>
<%@user.tyrants.each do |x|%>
    <ul>
    <li>
    <%= link_to x.name, tyrant_path(x.id)%><br/>
    </li>
    </ul>
   
<% end %>

<h3>My Comments</h3>
<%@user.comments.each do |c|%>
    <ul>
    <li>
    <%= link_to c.tyrant.name, tyrant_path(c.tyrant.id)%><br/>
    <%= c.comments%>
    </li>
    </ul>
   
<% end %>
<h3>My Reviews</h3>
<%@user.ratings.each do |x|%>
    
    <ul>
    <li>
    <%= link_to x.tyrant.name, rating_path(x.id) %><br/>
    <label>Appearance Rating:</label>
    <%= x.appearance_rating%><br/>
    <label>Economics Rating:</label>
    <%= x.economics_rating%><br/>
    <label>Social Rating:</label>
    <%= x.social_rating%><br/>
    <label>Warmongering Rating:</label>
    <%= x.warmongering_rating%><br/>
    <label>Charisma Rating:</label>
    <%= x.charisma_rating%><br/>
    </li>
    </ul>
    
    
<%end%>
</body>